### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by aviyall** [skyfortress/skytunnel#1]
Wish I had found this repo earlier; I really like it and I'm a fan of it now.
and i wanted to know if there is a feature for custom subdomain like offered by serveo

I am posting this as an issue because i found no other way to contact you.

**Comment by MusicaFM** [comment]
¿Solo puerto ofreces 443? ¿Qué pasa si otro usuario está usando tu puerto 443?

**Comment by skyfortress** [comment]
@aviyall custom subdomains are not supported right now, but I can add this feature.
@MusicaFM each client receives their own subdomain and connection proxy so they are not conflicting. Overall, port 443 is in command mostly for cosmetic purposes.

**Comment by aviyall** [comment]
@skyfortress  I will be waiting for this feature.

**Comment by skyfortress** [comment]
@aviyall deployed a new version with custom subdomain support. Check the README for usage instructions.

**Comment by aviyall** [comment]
Lately, serevo.net has had long downtimes. This is a solid alternative to Serveo. Thanks, brother!
